mod.id="serverflared"
mod.name="ServerFlared"
mod.group="me.gergerapex1"
mod.version="1.0.0"
mod.channel_tag="-beta.3"
mod.authors="GerGerAypex1"
mod.license="GPL3.0"
mod.description="Allows you to expose your Minecraft server using automatic Cloudflare Tunnel setup."
mod.sources_url="https://github.com/gergerapex1/serverflared"
mod.homepage_url="https://github.com/gergerapex1/serverflared"
mod.issues_url="https://github.com/gergerapex1/serverflared/issues"


["fabric"]
loader="0.12.0"

["26.1"]
loader.minecraft="26.1"
deps.minecraft.min="26.1"
deps.minecraft.max="26.1.4"


["26.1-fabric"]
deps.fabric-api="0.145.1+26.1"

["26.1-forge"]
loader.forge="62.0.9"

["26.1-neoforge"]
loader.neoforge="19-beta"

