[versions]
stonecutter = "0.9.6"
stonecutter-postprocess = "2.1-beta.8"
mod-publish = "1.1.0"
dotenv-gradle = "4.0.0"
foojay = "1.0.0"
fabric-loader = "0.17.3"
devtools-ksp = "2.3.9"
kotlin-jvm = "2.4.0"
fletching-table = "0.1.0-alpha.22"
moulberry-mixinconstraints = "1.1.0"
jackson = "2.15.2"
shadow = "9.3.0"
snakeyaml = "2.0"
jvmdowngrader="1.3.6"
unimined="1.4.2-SNAPSHOT"
architectury-loom = "1.15.50"
architectury-loom-pack200 = "0.1.3"
slf4j = "2.0.7"
[libraries]
kikugie-postprocess = { module = "dev.kikugie:postprocess", version.ref = "stonecutter-postprocess" }
mod-publish-plugin = { module = "me.modmuss50:mod-publish-plugin", version.ref = "mod-publish" }
kikugie-stonecutter = { module = "dev.kikugie:stonecutter", version.ref = "stonecutter" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
foojay-resolver = { module = "org.gradle.toolchains:foojay-resolver", version.ref = "foojay" }
fletching-table = { module = "dev.kikugie:fletching-table", version.ref = "fletching-table" }
moulberry-mixinconstraints = { module = "com.moulberry:mixinconstraints", version.ref = "moulberry-mixinconstraints" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
#build logic
jvmdowngrader = { module = "xyz.wagyourtail.jvmdowngrader:gradle-plugin", version.ref = "jvmdowngrader" }
architectury-loom = { module = "gg.essential.loom:gg.essential.loom.gradle.plugin", version.ref = "architectury-loom" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
[plugins]
stonecutter = { id = "dev.kikugie.stonecutter", version.ref = "stonecutter" }
dotenv = { id = "co.uzzu.dotenv.gradle", version.ref = "dotenv-gradle" }
jsonlang-postprocess = { id = "dev.kikugie.postprocess.jsonlang", version.ref = "stonecutter-postprocess" }
mod-publish-plugin = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools-ksp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
#fletching-table = { id = "dev.kikugie.fletching-table", version.ref = "fletching-table" }
gradleup-shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
jvmdowngrader = { id = "xyz.wagyourtail.jvmdowngrader", version.ref = "jvmdowngrader" }
architectury-loom-no-remap = { id = "gg.essential.loom", version.ref = "architectury-loom" }
architectury-loom = { id = "gg.essential.loom", version.ref = "architectury-loom" }
architectury-loom-pack200 = { id = "dev.architectury.architectury-pack200", version.ref = "architectury-loom-pack200" }
