package me.gergerapex1.serverflared;

// import org.slf4j.Logger;
// import org.slf4j.LoggerFactory;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
public class Constants {

	public static final String MOD_ID = "serverflared";
	public static final String MOD_FRIENDLY_NAME = "ServerFlared";
	public static final String MOD_VERSION = /*$ mod_version*/ "1.0.0";
	public static final Logger LOG = LogManager.getLogger(MOD_FRIENDLY_NAME);

	// Cloudflared related constants
	public static final String CLOUDFLARED_BINARY_NAME = "cloudflared";
	public static final String CLOUDFLARED_CERT_FILE = "cert.pem";
	public static final String CLOUDFLARED_DIR_NAME = ".cloudflared";
	public static final String BINARIES_DIR = "binaries";
	// Used for both mod config subdirectory and system cloudflared directories
	public static final String CONFIG_DIR = "cloudflared";

	// Cloudflared commands
	public static final String CMD_TUNNEL = "tunnel";
	public static final String CMD_LOGIN = "login";
	public static final String CMD_CREATE = "create";
	public static final String CMD_INFO = "info";
	public static final String CMD_ROUTE = "route";
	public static final String CMD_DNS = "dns";
	public static final String CMD_RUN = "run";
    public static final String CMD_LIST = "list";

	// Default values
	public static final String DEFAULT_TUNNEL_URL = "tcp://localhost:25565";
	public static final String TUNNEL_CONFIG_FILENAME = "cloudflare-tunnel-autogenerated.yml";
}
